customer: ""

aml_experiment_details:
  experiment_name: "zwerfafval_detectie"
  compute_name: gpu-inference-cluster
  env_name: zwerfafval_detectie
  env_version: 1
  src_dir: "."

inference_pipeline:
  model_params:
    batch_size: 1  # batch size does not have an effect for SAHI
    img_size: 1280  # [height, width]
    conf: 0.01
  inputs:
    datastore_path: "experiments"
    inference_data_rel_path: "zwerfafval/dataset_v1_extra_2/images/"
    model_weights_rel_path: "zwerfafval/train/yolo26s_1280_v1_extra_2_250/weights"
    model_name: "best.pt"
  outputs:
    datastore_path: "experiments"  # empty string "" means same as input datastore
    output_rel_path: "zwerfafval/predict/yolo26s_1280_v1_extra_2_250"
    detections_subfolder: ""
    labels_subfolder: ""
  target_classes: [0, 1, 2, 3]
  sensitive_classes: []
  target_classes_conf: null  # null means conf is taken from model_params
  sensitive_classes_conf: null  # null means conf is taken from model_params
  output_image_size: null  # [width, height] - null means keep original size
  save_detection_images: False
  save_detection_labels: True
  draw_bounding_boxes: True

training_pipeline:
  model_parameters:
    img_size: 1920
    batch: 2
    epochs: 250
    n_classes: 3
    name_classes: ["zwerfafval_grof", "zwerfafval_fijn", "grofvuil"]
    cache: True  # cache dataset in RAM
    patience: 0
    cos_lr: True
    seed: 0
    box: 7.5
    cls: 0.5
    dfl: 1.5
  inputs:
    datastore_path: "experiments"
    training_data_rel_path: "zwerfafval/dataset_v1-3_extra"
    model_weights_rel_path: "zwerfafval/model"
    model_name: "yolo26m.pt"
    model_config_file: "model_parameters.json" # can be an empty string or omitted entirely
  outputs:
    project_datastore_path: "experiments"
    project_rel_path: "zwerfafval/train"
    experiment_name: "yolo26m_1920_v1-2_extra_250"  # subfolder name to store results in, can be an empty string or omitted entirely
  run_prediction_best_model: True  # Whether to run the inference pipeline on on train/val/test using best.pt after training

logging:
  loglevel_own: INFO  # override loglevel for packages defined in `own_packages`
  own_packages: ["__main__", "zwerfafval_detectie"]
  basic_config:
    # log config as arguments to `logging.basicConfig`
    level: WARNING
    format: "%(asctime)s|||%(levelname)-8s|%(name)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
